[0]
sn = 0                                           # 云雀编号
type = "in_up"                                   # 机型,in_up为内顶,xn_side为侧面云雀,out_down为外底,out_up为外顶,out_lift为外侧二维往复机,out_rotate为外侧翻转轴,in_rotate为内侧翻转轴,out_fx为外侧仿形机,in_lift为内侧二维往复机,xn_updown为顶底云雀
x_position = 825                                # 原点相对于安装方向激光原点定位X,单位mm
z_position = 3820                                # 原点相对于安装方向激光原点定位Z,单位mm
spray_num = 1                                    # 喷枪数
axis_type = ["x"]                                # 轴类型, x为X轴, 喷枪装在x轴上
spray_radius = 80                                # 喷枪半径
x_status_offset = 0
out_front_x_offset = 100                         # 外侧前X轴偏移(当前设备未使用)
out_after_x_offset = 100                         # 外侧后X轴偏移(当前设备未使用)
in_front_x_offset = 50                          # 内侧前X轴偏移
in_after_x_offset = 50                          # 内侧后X轴偏移
out_up_y_offset = 100                            # 外侧上顶Y轴偏移(当前设备未使用)
out_down_y_offset = 100                          # 外侧下底Y轴偏移(当前设备未使用)
in_up_y_offset = 50                             # 内侧上顶Y轴偏移
in_down_y_offset = 100                           # 内侧下底Y轴偏移(当前设备未使用)
out_z_front_offset = 150                         # 外侧Z轴前定位偏移(当前设备未使用)
out_z_after_offset = 150                         # 外侧Z轴后定位偏移(当前设备未使用)
in_z_front_offset = 50                          # 内侧Z轴前定位偏移
in_z_after_offset = 50                          # 内侧Z轴后定位偏移
x_pos_speed = 500                                # X轴定位速度
x_recip_speed = 500                              # X轴往复速度
y_pos_speed = 100                                # Y轴定位速度
y_recip_speed = 100                              # Y轴往复速度
z_back_speed = 100                               # Z轴反喷速度(当前设备未使用)
z_zeroing_speed = 100                            # Z轴归零速度
outside_total_cycles = 2                         # 外侧往复喷涂次数
inside_total_cycles = 2                          # 内侧往复喷涂次数
recip_reduce_distance = 0                        # 往复减少距离(mm)
install_orietation = "right"                     # 安装方向
max_limit_speed = [500]                          # 最大速度, X轴
min_limit_pos = [0]                              # 最小限位, X轴
max_limit_pos = [950]                            # 最大限位, X轴
origin_pos = [3250]                              # 1个Y轴原点位置,单位mm
safe_pos = [0]                                   # 安全位置, X轴

[1]
sn = 1
type = "xn_side"
x_position = 510
z_position = 4990
spray_num = 6
axis_type = ["z", "y", "x1", "r1", "x2", "r2", "x3", "r3", "x4", "r4", "x5", "r5", "x6", "r6"]
spray_radius = 0
x_status_offset = 100
out_front_x_offset = 220
out_after_x_offset = 280
in_front_x_offset = 40
in_after_x_offset = 80
out_up_y_offset = 220
out_down_y_offset = 100
in_up_y_offset = 50
in_down_y_offset = 50
out_z_front_offset = 70
out_z_after_offset = 100
in_z_front_offset = 60
in_z_after_offset = 60
z_back_speed = 15
x_pos_speed = 500
x_recip_speed = 120
y_pos_speed = 100
y_recip_speed = 300
z_zeroing_speed = 200
outside_total_cycles = 2
inside_total_cycles = 2
recip_reduce_distance = 100
install_orietation = "right"
max_limit_speed = [250, 500, 500, 160]            # 最大速度, Z轴、Y轴、X轴(所有x1~x6共用)、R轴(所有r1~r6共用)
min_limit_pos = [0, 0, 0, -180]                   # 最小限位, Z轴、Y轴、X轴(所有x1~x6共用)、R轴(所有r1~r6共用)
max_limit_pos = [900, 430, 1000, 180]             # 最大限位, Z轴、Y轴、X轴(所有x1~x6共用)、R轴(所有r1~r6共用)
origin_pos = [1235, 1660, 2090, 2515, 2945, 3390] # 6个Y轴原点位置,单位mm
safe_pos = [0, 0, 0, 0]                           # 安全位置, Z轴、Y轴、X轴(所有x1~x6共用)、R轴(所有r1~r6共用)

[1.flat]
out_front_x_offset = 150
out_after_x_offset = 180
in_front_x_offset = 40
in_after_x_offset = 80
x_pos_speed = 500
x_recip_speed = 250
out_up_y_offset = 220
out_down_y_offset = 100
in_up_y_offset = 150
in_down_y_offset = 150
y_pos_speed = 100
y_recip_speed = 300
out_z_front_offset = 150
out_z_after_offset = 200
in_z_front_offset = 150
in_z_after_offset = 150
z_back_speed = 15
z_zeroing_speed = 200
outside_total_cycles = 1
inside_total_cycles = 1
recip_reduce_distance = 0
x_status_offset = 0

[2]
sn = 2
type = "out_down"
x_position = 320
z_position = 4090
spray_num = 1
axis_type = ["y", "x"]                           # 轴类型, y为Y轴, x为X轴
spray_radius = 80
x_status_offset = 0
out_front_x_offset = 0                         # 外侧前X轴偏移
out_after_x_offset = 150                         # 外侧后X轴偏移
in_front_x_offset = 100                          # 内侧前X轴偏移(当前设备未使用)
in_after_x_offset = 100                          # 内侧后X轴偏移(当前设备未使用)
out_up_y_offset = 100                            # 外侧上顶Y轴偏移(当前设备未使用)
out_down_y_offset = 100                          # 外侧下底Y轴偏移
in_up_y_offset = 100                             # 内侧上顶Y轴偏移(当前设备未使用)
in_down_y_offset = 100                           # 内侧下底Y轴偏移(当前设备未使用)
out_z_front_offset = 70                         # 外侧Z轴前定位偏移
out_z_after_offset = 100                         # 外侧Z轴后定位偏移
in_z_front_offset = 100                          # 内侧Z轴前定位偏移(当前设备未使用)
in_z_after_offset = 100                          # 内侧Z轴后定位偏移(当前设备未使用)
z_back_speed = 100                               # Z轴反喷速度(当前设备未使用)
x_pos_speed = 500
x_recip_speed = 500
y_pos_speed = 300
y_recip_speed = 100
z_zeroing_speed = 100
outside_total_cycles = 2
inside_total_cycles = 2
recip_reduce_distance = 0
install_orietation = "left"
max_limit_speed = [500, 500]                      # 最大速度, Y轴、X轴
min_limit_pos = [0, 0]                            # 最小限位, Y轴、X轴
max_limit_pos = [1200, 900]                       # 最大限位, Y轴、X轴
origin_pos = [1070]                               # 1个Y轴原点位置,单位mm
safe_pos = [0, 0]                                 # 安全位置, Y轴、X轴

[3]
sn = 3
type = "out_up"
x_position = 0
z_position = 4230
spray_num = 1
axis_type = ["y"]                                 # 轴类型, y为Y轴
spray_radius = 0
x_status_offset = 0
out_front_x_offset = 100                         # 外侧前X轴偏移(当前设备未使用)
out_after_x_offset = 100                         # 外侧后X轴偏移(当前设备未使用)
in_front_x_offset = 100                          # 内侧前X轴偏移(当前设备未使用)
in_after_x_offset = 100                          # 内侧后X轴偏移(当前设备未使用)
out_up_y_offset = 100                            # 外侧上顶Y轴偏移
out_down_y_offset = 100                          # 外侧下底Y轴偏移(当前设备未使用)
in_up_y_offset = 100                             # 内侧上顶Y轴偏移(当前设备未使用)
in_down_y_offset = 100                           # 内侧下底Y轴偏移(当前设备未使用)
out_z_front_offset = 50                         # 外侧Z轴前定位偏移
out_z_after_offset = 50                         # 外侧Z轴后定位偏移
in_z_front_offset = 100                          # 内侧Z轴前定位偏移(当前设备未使用)
in_z_after_offset = 100                          # 内侧Z轴后定位偏移(当前设备未使用)
z_back_speed = 100                               # Z轴反喷速度(当前设备未使用)
x_pos_speed = 100
x_recip_speed = 100
y_pos_speed = 100
y_recip_speed = 100
z_zeroing_speed = 100
outside_total_cycles = 2
inside_total_cycles = 2
recip_reduce_distance = 0
install_orietation = "right"
max_limit_speed = [500]                           # 最大速度, Y轴
min_limit_pos = [0]                               # 最小限位, Y轴
max_limit_pos = [0]                               # 最大限位, Y轴
origin_pos = [4000]                               # 1个Y轴原点位置,单位mm
safe_pos = [0]                                    # 安全位置, Y轴

[4]
sn = 4
type = "out_up"
x_position = 0
z_position = 4470
spray_num = 1
axis_type = ["y"]                                 # 轴类型, y为Y轴
spray_radius = 0
x_status_offset = 0
out_front_x_offset = 100                         # 外侧前X轴偏移(当前设备未使用)
out_after_x_offset = 100                         # 外侧后X轴偏移(当前设备未使用)
in_front_x_offset = 100                          # 内侧前X轴偏移(当前设备未使用)
in_after_x_offset = 100                          # 内侧后X轴偏移(当前设备未使用)
out_up_y_offset = 100                            # 外侧上顶Y轴偏移
out_down_y_offset = 100                          # 外侧下底Y轴偏移(当前设备未使用)
in_up_y_offset = 100                             # 内侧上顶Y轴偏移(当前设备未使用)
in_down_y_offset = 100                           # 内侧下底Y轴偏移(当前设备未使用)
out_z_front_offset = 50                         # 外侧Z轴前定位偏移
out_z_after_offset = 50                         # 外侧Z轴后定位偏移
in_z_front_offset = 100                          # 内侧Z轴前定位偏移(当前设备未使用)
in_z_after_offset = 100                          # 内侧Z轴后定位偏移(当前设备未使用)
z_back_speed = 100                               # Z轴反喷速度(当前设备未使用)
x_pos_speed = 100
x_recip_speed = 100
y_pos_speed = 100
y_recip_speed = 100
z_zeroing_speed = 100
outside_total_cycles = 2
inside_total_cycles = 2
recip_reduce_distance = 0
install_orietation = "left"
max_limit_speed = [500]                           # 最大速度, Y轴
min_limit_pos = [0]                               # 最小限位, Y轴
max_limit_pos = [0]                               # 最大限位, Y轴
origin_pos = [4000]                               # 1个Y轴原点位置,单位mm
safe_pos = [0]                                    # 安全位置, Y轴

[5]
sn = 5
type = "out_lift"
x_position = 0
z_position = 4970
spray_num = 1
axis_type = ["y"]                                 # 轴类型, y为Y轴
spray_radius = 0
x_status_offset = 0
out_front_x_offset = 300                         # 外侧前X轴偏移(当前设备未使用)
out_after_x_offset = 100                         # 外侧后X轴偏移(当前设备未使用)
in_front_x_offset = 100                          # 内侧前X轴偏移(当前设备未使用)
in_after_x_offset = 100                          # 内侧后X轴偏移(当前设备未使用)
out_up_y_offset = 100                            # 外侧上顶Y轴偏移(当前设备未使用)
out_down_y_offset = 100                          # 外侧下底Y轴偏移(当前设备未使用)
in_up_y_offset = 100                             # 内侧上顶Y轴偏移(当前设备未使用)
in_down_y_offset = 100                           # 内侧下底Y轴偏移(当前设备未使用)
out_z_front_offset = 300                         # 外侧Z轴前定位偏移
out_z_after_offset = 300                         # 外侧Z轴后定位偏移
in_z_front_offset = 100                          # 内侧Z轴前定位偏移(当前设备未使用)
in_z_after_offset = 100                          # 内侧Z轴后定位偏移(当前设备未使用)
z_back_speed = 100                               # Z轴反喷速度(当前设备未使用)
x_pos_speed = 100
x_recip_speed = 100
y_pos_speed = 100
y_recip_speed = 100
z_zeroing_speed = 100
outside_total_cycles = 2
inside_total_cycles = 2
recip_reduce_distance = 0
install_orietation = "left"
max_limit_speed = [500]                           # 最大速度, Y轴
min_limit_pos = [0]                               # 最小限位, Y轴
max_limit_pos = [0]                               # 最大限位, Y轴
origin_pos = [4000]                               # 1个Y轴原点位置,单位mm
safe_pos = [0]                                    # 安全位置, Y轴

[5.flat]
out_front_x_offset = 300
out_z_front_offset = 100
out_z_after_offset = 100
